In [1]:
import numpy as np

d = np.diag([1, 2, 3])
print(d)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [2]:

a = np.array([
    [1, 0, 0],
    [0, 5, 0],
    [0, 0, 9]
])

print(a)

[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [3]:

import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

C = A + B
print(C)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [6]:
A = [[1,2,3],[4,5,6],[7,8,9]]
B = [[9,8,7],[6,5,4],[3,2,1]]

C = [[A[i][j] + B[i][j]

      for j in range(3)]
     for i in range(3)]
print(C)

[[10, 10, 10], [10, 10, 10], [10, 10, 10]]


In [7]:
import numpy as np

A = np.array([
    [80, 75, 70],
    [85, 78, 72],
    [90, 88, 85]
])

B = np.array([
    [78, 80, 74],
    [82, 76, 70],
    [88, 90, 84]
])

print(A + B)

[[158 155 144]
 [167 154 142]
 [178 178 169]]


In [28]:
# diagonal

a =np.array ([[1,7,9,9],[2,4,7,8],[3,6,5,7],[7,7,7,7]])
print(a.shape)
f = 0
if a.shape[0] == a.shape[1]:
  s=0
  for i in a:
    f= f + i[s]
    s = s +1
    print(f)

else:
  print(f'diagonal adding not possible')



(4, 4)
1
5
10
17


In [29]:
# diagonal

a =np.array ([[1,7,9,9],[2,4,7,8],[3,6,5,7],[7,7,7,7]])
print(a)

[[1 7 9 9]
 [2 4 7 8]
 [3 6 5 7]
 [7 7 7 7]]


In [31]:
# reverse diagonal

import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

rev_diag = np.diag(np.fliplr(A))
print(rev_diag)




[3 5 7]


In [32]:
# reverse diagonal

a =np.array ([[1,7,9,9],[2,4,7,8],[3,6,5,7],[7,7,7,7]])


rev_diag = np.diag(np.fliplr(a))
print(rev_diag)


[9 7 6 7]
